In [1]:
# Import of libraries
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.preprocessing import StandardScaler

In [3]:
# Load the data
df = pd.read_csv("../data/BankChurners_CleanedMapped.csv", index_col="ClientID")
df.head()

,Attrited,Age,Gender,DependentCount,EducationLevel,MaritalStatus,IncomeCategory,CardCategory,RelationshipPeriod_InMonths,TotalProductNo,MonthsInactive_Last12Months,ContactNo_Last12Months,CreditLimit,TotalRevolvingBalance_CC,OpenToBuyAve_Last12Months,TransactionAmount_ChangeQ4overQ1,TotalTransactionAmount_Last12Months,TotalTransactionCount_Last12Months,TransactionCount_ChangeQ4overQ1,AveCardUtilizationRatio
ClientID,,,,,,,,,,,,,,,,,,,,
768805383,0,45,0,3,2,2,3,1,39,5,1,3,12691.0,777,11914.0,1.335,1144,42,1.625,0.061
818770008,0,49,1,5,4,1,1,1,44,6,1,2,8256.0,864,7392.0,1.541,1291,33,3.714,0.105
713982108,0,51,0,3,4,2,4,1,36,4,1,0,3418.0,0,3418.0,2.594,1887,20,2.333,0.000
769911858,0,40,1,4,2,0,1,1,34,3,4,1,3313.0,2517,796.0,1.405,1171,20,2.333,0.760
709106358,0,40,0,3,1,2,3,1,21,5,1,0,4716.0,0,4716.0,2.175,816,28,2.500,0.000